<a href="https://colab.research.google.com/github/code-r28/Coding-Practice/blob/main/Coding_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Day 1

In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,17).reshape(4,4)

#Transpose Matrix

In [ ]:
print("Matrix")

Matrix


In [ ]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print("Transpose of the Matrix")

Transpose of the Matrix


In [ ]:
print(A.transpose())

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


#Matrix Multiplication

In [ ]:
B=np.arange(18,34).reshape(4,4)

In [ ]:
A.dot(B) #Multiplcation function

array([[ 260,  270,  280,  290],
       [ 644,  670,  696,  722],
       [1028, 1070, 1112, 1154],
       [1412, 1470, 1528, 1586]])

In [ ]:
C=np.arange(35,51).reshape(4,4)

In [ ]:
# ABC=(AB)C=A(BC)
temp1=(A.dot(B).dot(C))
temp2=A.dot((B).dot(C))

In [ ]:
print(temp1)
print(temp2)

[[ 45300  46400  47500  48600]
 [112532 115264 117996 120728]
 [179764 184128 188492 192856]
 [246996 252992 258988 264984]]
[[ 45300  46400  47500  48600]
 [112532 115264 117996 120728]
 [179764 184128 188492 192856]
 [246996 252992 258988 264984]]


#Inverse Matrix

In [ ]:
arr=np.arange(91,107).reshape(4,4)
print(arr)

[[ 91  92  93  94]
 [ 95  96  97  98]
 [ 99 100 101 102]
 [103 104 105 106]]


In [ ]:
np.linalg.det(arr)

2.4233807008391215e-27

In [ ]:
np.linalg.inv(arr)

array([[ 2.34562481e+13, -8.66990291e+00, -7.03687442e+13,
         4.69124961e+13],
       [-2.86669922e+00, -7.03687442e+13,  1.40737488e+14,
        -7.03687442e+13],
       [-7.03687442e+13,  1.40737488e+14, -7.03687442e+13,
        -0.00000000e+00],
       [ 4.69124961e+13, -7.03687442e+13, -0.00000000e+00,
         2.34562481e+13]])

#Day 2


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/baseball.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/baseball.csv'

In [ ]:
df1=df.head(6)

In [ ]:
X=df1[['RS','RA','W','OBP','SLG','BA']]
Y=df1['OOBP']

In [ ]:
X=np.asmatrix(X)

In [ ]:
x=np.transpose(X)

In [ ]:
T=x.dot(x)

In [ ]:
inv=np.linalg.inv(T)

In [ ]:
theta=(inv.dot(X,T)).dot(Y)
print(theta)

In [ ]:
from sympy import *
x=Symbol ('x')
f=x**2
derivative=f.diff(x)
print (derivative)

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x=np.linspace (-10, 10, 100)
y=x**2
dy=2*x
fig, ax=plt.subplots()
ax.plot(x, y, 'r', linewidth=2)
ax.plot(x, dy, 'g',linewidth=2)
ax.legend(['y=x^2','dy/dx=2x'])

In [ ]:
x=Symbol('x')
f=x**2
integral=integrate(f,(x,0,1))
print(integral)

In [ ]:
x=np.linspace(0,1,100)
y=x**2

fig, ax=plt.subplots()
ax.fill_between(x,y)
plt.show()

#Binomial Distribution


In [ ]:
from scipy.stats import binom

In [ ]:
n=21
p=0.5

In [ ]:
binom_dist=binom(n,p)
even_probs=binom_dist.pmf(range(0,22,2))

In [ ]:
for i, prob in enumerate(even_probs):
  print("The Prob of getting {} head in 21 flips is {} ".format(2*i,prob))

In [ ]:
total_prob=sum(even_probs)
print("Total Prob of getting even num of head is {}".format(total_prob))

In [ ]:
#Plot a normal distribution for the height of men,mean-175,sd-6
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
mu,sigma=175,6
data=np.random.normal(mu,sigma,10000)

In [ ]:
sns.histplot(data,bins=30,kde=True,stat='probability')
plt.xlabel('Height(Men)')
plt.ylabel('Height(Prob)')
plt.title("Distribution of Men's height")
plt.xticks(range(155,200,5))
plt.show

In [ ]:
data=(data-mu)/sigma

In [ ]:
one_sd=len(data[(data>-1)&(data<1)])/len(data)*100
two_sd=len(data[(data>-2)&(data<2)])/len(data)*100
third_sd=len(data[(data>-3)&(data<3)])/len(data)*100

In [ ]:
print('Percentage of data withine one sd:',round(one_sd,2))
print('Percentage of data withine two sd:',round(two_sd,2))
print('Percentage of data withine third sd:',round(third_sd,2))

In [ ]:
sns.histplot(data,bins=30,kde=True,stat='probability')
plt.xlabel('Height(Men)')
plt.ylabel('Height(Prob)')
plt.title("Distribution of Men's height")
plt.xticks(range(-3,4,1))
plt.show

In [ ]:
from scipy.stats import norm

mu=175
sigma=5

In [ ]:
z=(183-mu)/sigma
p=norm.cdf(z)

In [ ]:
p=norm.cdf(z)
print("Percentage of men shorter than 183 cm:",round(p*100,2))

# Poisson Distribution

In [ ]:
#POISSION DISTRIBUTION
#plot poission distribution  with different values of lambda
from scipy.stats import poisson
import seaborn as sns
import matplotlib.pyplot as plt
#genreating poissiond data
sample1=poisson.rvs(mu=2,size=100)
sample2=poisson.rvs(mu=5,size=100)
sample3=poisson.rvs(mu=10,size=100)

In [ ]:
sns.kdeplot(x=sample1,fill=True,label='lambda=2')
sns.kdeplot(x=sample2,fill=True,label='lambda=5')
sns.kdeplot(x=sample3,fill=True,label='lambda=10')
plt.xlabel('No of events in a specific time interval')
plt.ylabel('Probability')
plt.legend()
plt.show()

In [ ]:
#a
from scipy.stats import poisson
#The expected Value lamda is the daily average rate
mu=3
#Calculate Probability of number of patients being 5 tmrw
p_5=poisson.pmf(k=5,mu=3)
print('Probability of 5 patients coming in tomorrow:', round(p_5*100,2))

In [ ]:
from scipy.stats import poisson

#Calculate probability of number of patients being >4 tmrw
greater_4=1-poisson.cdf(k=4,mu=3)
print('Prob of more than 4 patients:',round(greater_4*100,2))

In [ ]:
poisson_prob=[0]*25
print(poisson_prob)
#Number of customer ranging between 0 and 24
k_val=[i for i in range(0,25)]
lamda=5
for i in k_val:
     poisson_prob[i]=poisson.pmf(k=i,mu=lamda) #calculation poisson pmf for each value in k_val list
     #Displaying barplot to show poisson probability of k number of customer
plt.bar(k_val,poisson_prob)
plt.title(f"Poisson Distribution plot for Lamda: {lamda}")
plt.xlabel('Num of customer per day')
plt.ylabel('Probability')

In [ ]:
from scipy.stats import poisson

#Calculate probability of number of patients being >4 tmrw
greater_4=1-poisson.cdf(k=4,mu=3)
print('Prob of more than 4 patients:',round(greater_4*100,2))poisson_prob=[0]*25
print(poisson_prob)
#Number of customer ranging between 0 and 24
k_val=[i for i in range(0,25)]
lamda=5
for i in k_val:
     poisson_prob[i]=poisson.pmf(k=i,mu=lamda) #calculation poisson pmf for each value in k_val list
     #Displaying barplot to show poisson probability of k number of customer
plt.bar(k_val,poisson_prob)
plt.title(f"Poisson Distribution plot for Lamda: {lamda}")
plt.xlabel('Num of customer per day')
plt.ylabel('Probability')

#Numpy

In [ ]:
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]


sam_arr= np.array([l1,l2,l3])
print("Numpy multi dim arra\n",sam_arr)



Numpy multi dim arra
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
nd_arr=np.arange(12).reshape(4,3)
print(nd_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
tup=(1,2,3,4,5)
print("Tuple Values:",tup,"type",type(tup))
num_arr=np.array((tup))
print("Numpy Array values:",num_arr,"type",type(num_arr))

Tuple Values: (1, 2, 3, 4, 5) type <class 'tuple'>
Numpy Array values: [1 2 3 4 5] type <class 'numpy.ndarray'>


In [ ]:
arr_zd=np.array(36)
print(arr_zd)

36


In [ ]:
print("Arr one d",np.array([1,2,3,4,5]))

Arr one d [1 2 3 4 5]


In [ ]:
print("Arr two d",np.array([1,2,3,4,5]))

In [ ]:
print("Arr three d",np.array([1,2,3,4,5]))

#DS_Numpy


In [3]:
import numpy as np
zeros = np.zeros(10)
ones = np.ones(10)
fives = 5 * np.ones(10)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Fives:\n", fives)

result = np.concatenate((zeros, ones, fives))
print("Combined",result)

Zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
Combined [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [4]:
names = ['ram', 'paul', 'saran', 'sahara', 'renu', 'jeevi']
n_array = np.array(names)

print(n_array)

['ram' 'paul' 'saran' 'sahara' 'renu' 'jeevi']


In [7]:
data = [[21, 22, 23, 34], [5, 6, 7, 8]]
matrix = np.array(data).reshape(2, 4)
print(matrix)

[[21 22 23 34]
 [ 5  6  7  8]]


In [8]:
numbers = np.arange(2, 11)
matrix = numbers.reshape(3, 3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
sample_array = np.array([1, 2, 3, 4])

repeated_2_times = np.repeat(sample_array, 2)
print(repeated_2_times)

repeated_3_times = np.repeat(sample_array, 3)
print(repeated_3_times)

[1 1 2 2 3 3 4 4]
[1 1 1 2 2 2 3 3 3 4 4 4]


In [10]:
array = np.array([[2, 4, 6], [6, 8, 10]])
fourth_element = array.flatten()[3]

print("Forth element of the array:", fourth_element)

Forth element of the array: 6


In [11]:
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])
result = np.column_stack((array1, array2))
print(result)

[[10 40]
 [20 50]
 [30 60]]


In [12]:
all_numbers = np.arange(30, 71)

even_numbers = all_numbers[all_numbers % 2 == 0]

print(even_numbers)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
array = np.array([1, 2, np.nan, 4, np.nan, 6])

nan_elements = np.isnan(array)

print("Original array:")
print(array)
print("Element-wise NaN test:")
print(nan_elements)


Original array:
[ 1.  2. nan  4. nan  6.]
Element-wise NaN test:
[False False  True False  True False]


In [15]:
input_array = np.array([2, 4, 6, 8, 10, 12])
output_array = input_array[::-1]
print(output_array)


[12 10  8  6  4  2]
